name: Publish image

on:
  push

jobs:
  build:
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    uses: UMRoboticsTeam/umrt-ci-cd/.github/workflows/docker-build.yaml@reusable-docker-build
    secrets:
      APT_SERVER_NAME: raw.githubusercontent.com
      APT_SIGNING_PUBKEY: ${{ secrets.APT_SIGNING_PUBKEY }}
      APT_RETRIEVE_USER: ${{ secrets.APT_RETRIEVE_USER }}
      APT_RETRIEVE_TOKEN: ${{ secrets.APT_RETRIEVE_TOKEN }}
